### PR TITLE
Finishing compilation engine

### PR DESCRIPTION
**Pull request by h-lame**
Get the compilation engine to the point where it can compile all the example programs in nand2tetris/projects/11/ !

The commit notes tell good stories about the pain some of this took.  

Caveats: I've mostly just been concerned with getting the thing done, not with good design.  If anyone wants to refactor onwards that would be grand.

### CODE REVIEW

**Comment by floehopper** [comment]
Wow! A truly heroic effort!

**Comment by leocassarani** [comment]
This is incredible, and the test suite looks really comprehensive, too. Thanks Murray!

Are we all happy to merge this in as the first order of business at the next meeting on Tuesday?

**Comment by tomstuart** [comment]
So good. Very happy to merge next meeting.

**Comment by h-lame** [comment]
Aw, shucks; that's very kind.  It's unlikely that I'll be at the next meeting (:saddest_possible_face:) so I won't be able to explain / defend / apologise for / &c any of the decisions I've made in this code.  Feel free to ask about them here or on the mailing list, or just pretend it's not a problem.

**Comment by tuzz** [comment]
This is fantastic. A truly heroic effort. I think we should spend some time at the start of the meeting walking through Murray's work. :+1: :zap:

**Comment by leocassarani** [comment]
Kevin:

> This is awesome

James:

> Don't get cocky, kid.

We're merging this.

**Pull request merged**
